---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: secret-config
  namespace: wealthfolio
spec:
  target:
    name: wealthfolio
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        secret-key: "{{ .secretKey }}"
        password-hash: "{{ .passwordHash }}"
  data:
    - secretKey: secretKey
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: 5663a686-bb6f-48a0-bfa3-5e48f3c46883
        metadataPolicy: None
        property: password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
    - secretKey: passwordHash
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: 10c90d18-9aa3-4646-84e5-25c52766ddf9
        metadataPolicy: None
        property: password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
